# ===========================
# Mercado Yuli Online
# ===========================
spring.application.name=Mercado Yuli Online

# Servidor
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ===========================
# PostgreSQL Local
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/yuliBD
spring.datasource.username=postgres
spring.datasource.password=30334006
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
